### ISSUE TITLE
Look in to using MirGeneDB

### ISSUE THREAD

**Issue by ewels** [nf-core/smrnaseq#12]
Potential alternative to using miRbase - instead the curated http://mirgenedb.org/

**Comment by shashwatsahay** [comment]
Can I already use this by providing the --mature, --harpin --mirna_gtf from MirGeneDB?

**Comment by lpantano** [comment]
Hi, I am not sure it will work as it is since the format is a little bit
different, but I never tried. If you can help with the integration, it will
be great!



From: Shashwat Sahay <notifications@github.com> <notifications@github.com>
Reply: nf-core/smrnaseq
<reply@reply.github.com>
<reply@reply.github.com>
Date: January 14, 2020 at 10:40:53 AM
To: nf-core/smrnaseq <smrnaseq@noreply.github.com>
<smrnaseq@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  Re: [nf-core/smrnaseq] Look in to using MirGeneDB (#12)

Can I already use this by providing the --mature, --harpin --mirna_gtf from
MirGeneDB?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nf-core/smrnaseq/issues/12?email_source=notifications&email_token=AAML6HBSCAFQTKSHT6WQA7LQ5XMIJA5CNFSM4GXOWIG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEI5CFMA#issuecomment-574235312>,
or unsubscribe

**Comment by apeltzer** [comment]
Done in #146
