### ISSUE TITLE
casting bug Error in MIRTRACE_RUN

### ISSUE THREAD

**Issue by shivani303** [nf-core/smrnaseq#262]
### Description of the bug

Dear all,
I have tried running the smRNA nf-core pipeline but I got error in MIRTRACE_RUN.
Does that sound familiar to anyone? Or do you have an idea how to approach this?
Any help is highly appreciated.
I have attached the command used and the terminal output also.
Thanks a lot,

### Command used and terminal output

```console
*command used*
sudo ./nextflow run nf-core/smrnaseq -r 2.2.1 -profile docker --input 's3://temp-test.bucket/mirna_test/sample_1.csv' --genome 'GRCh38' --mirgenedb_species 'hsa' --mirgenedb_gff 's3://temp-test.bucket/mirna_test/mirgenedb_files/hsa.gff.gz' --mirgenedb_mature 's3://temp-test.bucket/mirna_test/mirgenedb_files/has.fa.gz' --mirgenedb_hairpin 's3://temp-test.bucket/mirna_test/mirgenedb_files/hsa-pre.fa.gz' --protocol 'illumina' --outdir 's3://temp-test.bucket/mirna_test/result_mirna/' --three_prime_adapter "TGGAATTCTCGGGTGCCAAGG" -bg

**terminal output**
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: null.

The full error message was:

Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRTRACE:MIRTRACE_RUN (1)'

Caused by:
  Cannot cast object 'SRR25223577.fastp.fastq.gz' with class 'nextflow.processor.TaskPath' to class 'java.util.List' -- Check script '/root/.nextflow/assets/nf-core/smrnaseq/./workflows/../subworkflows/local/../../modules/local/mirtrace.nf' at line: 28

Source block:
  def primer = adapter ? "--adapter ${adapter}" : ""
  def protocol = params.protocol == 'custom' ? '' : "--protocol $params.protocol"
  def java_mem = ''
  if(task.memory){
          tmem = task.memory.toBytes()
          java_mem = "-Xms${tmem} -Xmx${tmem}"
      }
  def config_lines = [ids,reads]
      .transpose()
      .collect({ id, path -> "echo '${path},${id}' >> mirtrace_config" })
  """
      export mirtracejar=\$(dirname \$(which mirtrace))
  
      ${config_lines.join("\n    ")}
  
      java $java_mem -jar \$mirtracejar/mirtrace.jar --mirtrace-wrapper-name mirtrace qc  \\
          --species $params.mirtrace_species \\
          $primer \\
          $protocol \\
          --config mirtrace_config \\
          --write-fasta \\
          --output-dir mirtrace \\
          --force
  
      cat <<-END_VERSIONS > versions.yml
      ${task.process}":
          mirtrace: \$(echo \$(mirtrace -v 2>&1))
      END_VERSIONS
      """
```

**Comment by sguizard** [comment]
This error is caused by fastp that do not detect adapters in a sample. 

To solve this issue, you need to specify the `--three_prime_adapter` parameter. 
In my case, I had one sample where fastp could not auto detect the adapter. Because of that, the data of mirtrace input channel are into two tuples instead of one. The additional tuple contains a null value that causes the mentioned error. 

My samples have qiaseq adapter. So, I added `--three_prime_adapter AACTGTAGGCACCATCAAT` to my command line. 

This force this pipeline to set the `--adapter_sequence AACTGTAGGCACCATCAAT` for `fastp` program. This way the adapter is correctly removed from the reads, the adapter sequence is correctly extracted from the json file and transmitted in the output channel.

**Comment by quasi-deus** [comment]
I am getting the exact same error and I would like to know how can I go about running this for the test_full configuration.

**Comment by apeltzer** [comment]
Should not be an issue anymore, in case it persists, please open a new issue for this 👍🏻
