### ISSUE TITLE
Error: Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)

### ISSUE THREAD

**Issue by mdozmorov** [nf-core/smrnaseq#283]
### Description of the bug

```
WARN: Input tuple does not match input set cardinality declared by process `NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_RUN` -- offending value: /path/to/work/eb/4e5e3a3fa9f24739561950cae26c27/genome.edited.fa
ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:SMRNASEQ:MIRDEEP2:MIRDEEP2_RUN (1)'

Caused by:
  Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)
```

This error is reproducible after `nextflow clean nf-core/smrnaseq` and restarting in the new folder. I'm running the latest nextflow and the pipeline (2.2.3). Skipping this step with `--skip_mirdeep` helps, but without it the error persists.

### Command used and terminal output

```console
nextflow run nf-core/smrnaseq --input ${INPUT} \
  --outdir ${DIROUT} \
  -profile 'singularity' \
  --genome GRCh38 \
  --mirtrace_species 'hsa' \
  --protocol 'illumina'
```

### System information

nextflow version 23.04.3.5875
HPC
local
singularity
CentOS 7
2.2.3

**Comment by macrobiotus** [comment]
Dear all, thank you for working on this pipeline. I can confirm this from here. Admittedly I keep checking for version 2.2.4 as 2.2.3 doesn't seem to work very well ever since the miRbase links changed.

![Screenshot 2023-09-25 at 13 29 35](https://github.com/nf-core/smrnaseq/assets/10920135/7b61ffe6-2af0-44e1-907d-e522606cb677)
![Screenshot 2023-09-25 at 13 30 17](https://github.com/nf-core/smrnaseq/assets/10920135/c32918d0-03d0-4ee2-9f47-616e78d7b05d)
![Screenshot 2023-09-25 at 13 31 25](https://github.com/nf-core/smrnaseq/assets/10920135/77846b70-5eed-4170-a5a7-6d758393c5ca)

**Comment by apeltzer** [comment]
Should be fine with dev now
