### ISSUE TITLE
mirdeep2_run error

### ISSUE THREAD

**Issue by yangfeizZZ** [nf-core/smrnaseq#289]
### Description of the bug

when i nun:
nextflow run nf-core/smrnaseq -profile docker --input samplesheet.csv --genome 'GRCm38' --mirtrace_species 'mmu' --outdir ../J1EV_S1_result/ 
 i got an error:
![微信截图_20230924083613](https://github.com/nf-core/smrnaseq/assets/91297170/af75c844-9592-45d9-bc73-e2ced6674d00)
I don't know why~

**Comment by marchoeppner** [comment]
This is caused by:

https://github.com/nf-core/smrnaseq/blob/18d6c84926a3c983d4d9518a53020a7791746c98/modules/local/format_fasta_mirna.nf#L16

The mission from this process, pre-formatting the mirna data, emits a [ hash, file ] Channel, while mirdeep_run expects only [ file ] here:

https://github.com/nf-core/smrnaseq/blob/18d6c84926a3c983d4d9518a53020a7791746c98/modules/local/mirdeep2_run.nf#L15

Same for the 'mature' fasta input.

As a workaround, you can just edit the module to update the input structure for those two channels.

**Comment by yangfeizZZ** [comment]
> This is caused by:
> 
> https://github.com/nf-core/smrnaseq/blob/18d6c84926a3c983d4d9518a53020a7791746c98/modules/local/format_fasta_mirna.nf#L16
> 
> The emission from this process, pre-formatting the mirna data, emits a [ hash, file ] Channel, while mirdeep_run expects only [ file ] here:
> 
> https://github.com/nf-core/smrnaseq/blob/18d6c84926a3c983d4d9518a53020a7791746c98/modules/local/mirdeep2_run.nf#L15
> 
> Same for the 'mature' fasta input.
> 
> As a workaround, you can just edit the module to update the input structure for those two channels.

sorry,i am not good at nextflow. I can't understand fully what you explain. I also don't know how to solve it. Would mind me help me more carefully and use a sample word to say.
Thank you~~~

**Comment by marchoeppner** [comment]
Right, apologies, I am not a developer in this project and if the code base is unfamiliar to you, it would probably prove complicated to sort this out remotely. 

Have you tried running this pipeline in an older version? I am not 100% sure when this issue was introduced, but presumably it did not exist on older stable releases

Just rerun with something like:
nextflow run nf-core/smrnaseq -r 2.1.0 ...

**Comment by yangfeizZZ** [comment]
> Right, apologies, I am not a developer in this project and if the code base is unfamiliar to you, it would probably prove complicated to sort this out remotely.
> 
> Have you tried running this pipeline in an older version? I am not 100% sure when this issue was introduced, but presumably it did not exist in older stable releases
> 
> Just rerun with something like: nextflow run nf-core/smrnaseq -r 2.1.0 ...

I download this pipeline on my linux, and the version is 2.2.3

**Comment by subrahmanya-nayak** [comment]
@yangfeizZZ Did you get any solutions for this?

**Comment by apeltzer** [comment]
Should be fine on dev already, if not let us know
