### ISSUE TITLE
Possible bug in logic code related to mature, hairpin and species setup

### ISSUE THREAD

**Issue by lpantano** [nf-core/smrnaseq#414]
### Description of the bug

For this [PR](https://github.com/nf-core/smrnaseq/pull/386) I realized that I can see there are a few things that will generate problems due to the duality between

- params.mirtrace_species 
- params.mirna_gtf
- params.mature
- params.hairpin
- params.mirgenedb_*

 `params.mirtrace_species` is used for miRTrace.
 `params.mirtrace_species`  is re-used for mirtop_quant when `params.mature` and `params.hairpin` and `params.mirna_gtf`  are set up

all the `params.mirgendb_*` is used for mirtop_quant when they are set.

So the logic should be:

you set up `params.mirgendb_*` or  `params.mirna_gtf`, `params.mature`, `params.hairpin`, not both.

you set up `params.mirtrace_species`  if you want to use miRTrace or default miRBase files(`params.mirna_gtf, params.mature, params.hairpin`)

if user set up `params.mirgendb_*` and wants to run miRTrace, then `params.mirtrace_species` is used with miRTrace and `params.mirgendb_species` is used with miRTop. I don't think this is happening right. 

Maybe we need a meeting to sort this out?

**Comment by nschcolnicov** [comment]
I think this should be fixed simply by updating the line mentioned by Lorena:
https://github.com/nf-core/smrnaseq/blob/874ef646adb9f93ebf000788e1f48225a0efff2f/subworkflows/local/prepare_genome/main.nf#L37
with something like this:
```
ch_mirna_gtf              = val_mirna_gtf                 ?  Channel.fromPath(val_mirna_gtf, checkIfExists: true).collect() : ( mirna_gtf_from_species ? Channel.fromPath(mirna_gtf_from_species, checkIfExists: true).collect() :  Channel.empty() )
```

But we probably would need to update the CI tests as well, and check if there is any other issue that arises from this change

**Comment by lpantano** [comment]
I think this issue is a little bit bigger scope. This is about how the pipeline setup the variables whether people want to use miRBase files or mirgeneDB, and together with miRTrace. I didn't test it but , I don't think will work well. When I run test_mirgendb config file, **mirtop** **doesn't run**, because **mirtrace_species** **is not setup**. But it should run, actually **mirtrace** **should be able to run** as well, even if people use mirgendb file to quantify.

**Comment by atrigila** [comment]
The issue was solved in https://github.com/nf-core/smrnaseq/pull/386 but some improvements in design can be made regarding the use of these databases in the future. 
Some ideas discussed are:

- Use a single channel with hairpin, mature, gtf and species. This channel can have an associated metamap adding the origin DB (mirgeneDB or other) for tracking. 
- There could be some checks that ensure that the 3 files come from the same database.
- The checks will also ensure that one single channel is populated and used across the whole pipeline. We could avoid having several params/channels referring to similar information. This is similar to what is done will the protocols. 
- The species can likely be "translated" from other databases to mirTrace nomenclature by removing/adding a capital letter at the beginning (e.g. "hsa" to "Hsa"). 
- The gtf from each species could obtained automatically from these DBs using getGenomeAttribute() as we do with iGenomes.

**Comment by nschcolnicov** [comment]
Closing this ticket, as the issue described was solved in https://github.com/nf-core/smrnaseq/pull/386. @lpantano Feel free to open a new one, if you think there was something else to work on
