### ISSUE TITLE
pipeline fails at same step each time 

### ISSUE THREAD

**Issue by lo-schwartz** [nf-core/smrnaseq#453]
I have tried this pipeline multiple times but it fails at the same step every time. It does not complete and I am not sure why. 
[09_30_nextflow.log.1.pdf](https://github.com/user-attachments/files/17197348/09_30_nextflow.log.1.pdf)

**Comment by lo-schwartz** [comment]
I tried using it with -r 2.3.1 \ but I am on an HPC and I do not think I will be able to use docker. I tried it again with singularity and it failed again the same way even with the version change.

**Comment by nschcolnicov** [comment]
Hi @lo-schwartz I tried to run the pipeline using your settings and wasn't able to reproduce the error.

Also. looking at the log:
``NFCORE_SMRNASEQ:MIRNA_QUANT:BAM_STATS_HAIRPIN:BAM_STATS_SAMTOOLS:SAMT
OOLS_FLAGSTAT (BT474-7_mature_hairpin)` terminated with an error exit
status (151)`
I think that the issue seems to be related to what @atrigila posted: https://github.com/nextflow-io/nextflow/discussions/4272.

**Comment by apeltzer** [comment]
Looks indeed like an issue with LSF + Singularity and not with the pipeline. Also tried your parameters with some samples and it passed / worked fine for me :-(
